import chalk from 'chalk';
import { FixSuggestion } from './fix-suggester';

export class OutputFormatter {
    /**
     * Format fix suggestions for console output with colors
     */
    static formatConsoleOutput(suggestion: FixSuggestion): string {
        let output = '';

        // Header
        output += chalk.blue.bold('\n' + '='.repeat(80) + '\n');
        output += chalk.blue.bold('🔧 BUG FIX SUGGESTIONS\n');
        output += chalk.blue.bold('='.repeat(80) + '\n\n');

        // Analysis section
        output += chalk.green.bold('📋 ROOT CAUSE ANALYSIS\n');
        output += chalk.green('─'.repeat(80) + '\n');
        output += chalk.white(suggestion.analysis) + '\n\n';

        // Affected files
        if (suggestion.affectedFiles.length > 0) {
            output += chalk.yellow.bold('📁 AFFECTED FILES\n');
            output += chalk.yellow('─'.repeat(80) + '\n');
            suggestion.affectedFiles.forEach(file => {
                output += chalk.yellow(`  • ${file}\n`);
            });
            output += '\n';
        }

        // Fixes
        output += chalk.cyan.bold('🛠️  SUGGESTED FIXES\n');
        output += chalk.cyan('─'.repeat(80) + '\n\n');

        suggestion.fixes.forEach((fix, index) => {
            output += chalk.magenta.bold(`Fix ${index + 1}: ${fix.filePath}\n`);

            if (fix.explanation) {
                output += chalk.white(fix.explanation) + '\n\n';
            }

            // Format diff with colors
            output += this.formatDiffWithColors(fix.diff) + '\n\n';
        });

        // Footer
        output += chalk.blue.bold('='.repeat(80) + '\n');
        output += chalk.gray('💡 Tip: Review the diffs carefully before applying them to your code.\n');
        output += chalk.blue.bold('='.repeat(80) + '\n');

        return output;
    }

    /**
     * Format diff with syntax highlighting
     */
    private static formatDiffWithColors(diff: string): string {
        const lines = diff.split('\n');
        return lines.map(line => {
            if (line.startsWith('+++') || line.startsWith('---')) {
                return chalk.bold(line);
            } else if (line.startsWith('+')) {
                return chalk.green(line);
            } else if (line.startsWith('-')) {
                return chalk.red(line);
            } else if (line.startsWith('@@')) {
                return chalk.cyan(line);
            } else {
                return chalk.gray(line);
            }
        }).join('\n');
    }

    /**
     * Format as pure unified diff for file output
     */
    static formatDiffFile(suggestion: FixSuggestion): string {
        return suggestion.diffOutput;
    }

    /**
     * Format as markdown report
     */
    static formatMarkdownReport(
        suggestion: FixSuggestion,
        bugDescription: string,
        runId: string
    ): string {
        let markdown = `# Fix Analysis Report

**Run ID**: ${runId}  
**Bug**: ${bugDescription}  
**Generated**: ${new Date().toISOString()}

---

## Root Cause Analysis

${suggestion.analysis}

---

## Affected Files

`;

        suggestion.affectedFiles.forEach(file => {
            markdown += `- \`${file}\`\n`;
        });

        markdown += `\n---\n\n## Suggested Fixes\n\n`;

        suggestion.fixes.forEach((fix, index) => {
            markdown += `### ${index + 1}. ${fix.filePath}\n\n`;

            if (fix.explanation) {
                markdown += `${fix.explanation}\n\n`;
            }

            markdown += `**Diff:**\n\n\`\`\`diff\n${fix.diff}\n\`\`\`\n\n`;
        });

        markdown += `---\n\n## How to Apply\n\n`;
        markdown += `### Option 1: Manual Application\n\n`;
        markdown += `Review each diff and manually apply the changes to your code.\n\n`;
        markdown += `### Option 2: Using git apply\n\n`;
        markdown += `Save the \`suggested-fixes.diff\` file and apply it:\n\n`;
        markdown += `\`\`\`bash\n`;
        markdown += `cd test-app  # or your codebase directory\n`;
        markdown += `git apply ../packages/runner/runs/${runId}/suggested-fixes.diff\n`;
        markdown += `\`\`\`\n\n`;
        markdown += `### Option 3: Using patch\n\n`;
        markdown += `\`\`\`bash\n`;
        markdown += `cd test-app\n`;
        markdown += `patch -p1 < ../packages/runner/runs/${runId}/suggested-fixes.diff\n`;
        markdown += `\`\`\`\n\n`;

        markdown += `---\n\n## Verification\n\n`;
        markdown += `After applying the fixes:\n\n`;
        markdown += `1. Restart your application\n`;
        markdown += `2. Test the specific scenario that was causing the bug\n`;
        markdown += `3. Verify that the issue is resolved\n`;
        markdown += `4. Run any relevant test suites\n\n`;

        markdown += `---\n\n`;
        markdown += `*Generated by BugBot Fix Suggester*\n`;

        return markdown;
    }

    /**
     * Format a summary for quick viewing
     */
    static formatSummary(suggestion: FixSuggestion, verbose: boolean = false): string {
        let summary = '';

        summary += chalk.green.bold('\n✅ Fix suggestions generated successfully!\n\n');
        summary += chalk.white(`📊 Summary:\n`);
        summary += chalk.gray(`   • Affected files: ${suggestion.affectedFiles.length}\n`);
        summary += chalk.gray(`   • Total fixes: ${suggestion.fixes.length}\n\n`);

        if (verbose) {
            summary += chalk.white(`📁 Files to modify:\n`);
            suggestion.affectedFiles.forEach(file => {
                summary += chalk.cyan(`   • ${file}\n`);
            });
            summary += '\n';
        }

        return summary;
    }
}
